version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install --upgrade pip
      - pip install -r requirements.txt -t ./package

  build:
    commands:
      - rsync -av --exclude package ./ ./package/
      - cd package
      - zip -r ../app.zip .
      

artifacts:
  files:
    - app.zip
